name: Sync GitHub to Azure DevOps

on:
  push:
    branches:
      - main  # or the branch you want to sync with Azure DevOps

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"

    - name: Add Azure DevOps as remote
      run: |
        git remote add azure  https://DEMObirendar@dev.azure.com/DEMObirendar/DEMO/_git/DEMO
        git fetch azure

    - name: Push code to Azure DevOps
      run: |
        git push azure main  # or your branch name
